-- ============================================================================
-- TPCH Data Product: Curated & Gold Layers
-- Compatible with all Snowflake account types (including trial)
-- No Cortex AI functions used
-- ============================================================================

-- ============================================================================
-- SETUP: Database, Schema, Warehouse
-- ============================================================================
USE ROLE ACCOUNTADMIN;

CREATE DATABASE IF NOT EXISTS TPCH_DATA_PRODUCT;
CREATE SCHEMA IF NOT EXISTS TPCH_DATA_PRODUCT.CURATED;
CREATE SCHEMA IF NOT EXISTS TPCH_DATA_PRODUCT.GOLD;
CREATE WAREHOUSE IF NOT EXISTS COMPUTE_WH
    WAREHOUSE_SIZE = 'XSMALL'
    AUTO_SUSPEND = 60
    AUTO_RESUME = TRUE;

USE WAREHOUSE COMPUTE_WH;

-- ============================================================================
-- CURATED LAYER (Silver): Cleaned, joined, enriched base tables
-- ============================================================================

CREATE OR REPLACE TABLE TPCH_DATA_PRODUCT.CURATED.DIM_CUSTOMER AS
SELECT
    c.C_CUSTKEY AS CUSTOMER_KEY,
    c.C_NAME AS CUSTOMER_NAME,
    c.C_MKTSEGMENT AS MARKET_SEGMENT,
    c.C_ACCTBAL AS ACCOUNT_BALANCE,
    c.C_PHONE AS PHONE,
    n.N_NAME AS NATION,
    r.R_NAME AS REGION
FROM SNOWFLAKE_SAMPLE_DATA.TPCH_SF1.CUSTOMER c
JOIN SNOWFLAKE_SAMPLE_DATA.TPCH_SF1.NATION n ON c.C_NATIONKEY = n.N_NATIONKEY
JOIN SNOWFLAKE_SAMPLE_DATA.TPCH_SF1.REGION r ON n.N_REGIONKEY = r.R_REGIONKEY;

CREATE OR REPLACE TABLE TPCH_DATA_PRODUCT.CURATED.DIM_SUPPLIER AS
SELECT
    s.S_SUPPKEY AS SUPPLIER_KEY,
    s.S_NAME AS SUPPLIER_NAME,
    s.S_ACCTBAL AS ACCOUNT_BALANCE,
    s.S_PHONE AS PHONE,
    n.N_NAME AS NATION,
    r.R_NAME AS REGION
FROM SNOWFLAKE_SAMPLE_DATA.TPCH_SF1.SUPPLIER s
JOIN SNOWFLAKE_SAMPLE_DATA.TPCH_SF1.NATION n ON s.S_NATIONKEY = n.N_NATIONKEY
JOIN SNOWFLAKE_SAMPLE_DATA.TPCH_SF1.REGION r ON n.N_REGIONKEY = r.R_REGIONKEY;

CREATE OR REPLACE TABLE TPCH_DATA_PRODUCT.CURATED.DIM_PART AS
SELECT
    p.P_PARTKEY AS PART_KEY,
    p.P_NAME AS PART_NAME,
    p.P_MFGR AS MANUFACTURER,
    p.P_BRAND AS BRAND,
    p.P_TYPE AS PART_TYPE,
    p.P_SIZE AS PART_SIZE,
    p.P_RETAILPRICE AS RETAIL_PRICE
FROM SNOWFLAKE_SAMPLE_DATA.TPCH_SF1.PART p;

CREATE OR REPLACE TABLE TPCH_DATA_PRODUCT.CURATED.FCT_ORDER_LINEITEM AS
SELECT
    o.O_ORDERKEY AS ORDER_KEY,
    o.O_CUSTKEY AS CUSTOMER_KEY,
    o.O_ORDERSTATUS AS ORDER_STATUS,
    o.O_ORDERDATE AS ORDER_DATE,
    o.O_ORDERPRIORITY AS ORDER_PRIORITY,
    l.L_LINENUMBER AS LINE_NUMBER,
    l.L_PARTKEY AS PART_KEY,
    l.L_SUPPKEY AS SUPPLIER_KEY,
    l.L_QUANTITY AS QUANTITY,
    l.L_EXTENDEDPRICE AS EXTENDED_PRICE,
    l.L_DISCOUNT AS DISCOUNT,
    l.L_TAX AS TAX,
    l.L_RETURNFLAG AS RETURN_FLAG,
    l.L_LINESTATUS AS LINE_STATUS,
    l.L_SHIPDATE AS SHIP_DATE,
    l.L_COMMITDATE AS COMMIT_DATE,
    l.L_RECEIPTDATE AS RECEIPT_DATE,
    l.L_SHIPMODE AS SHIP_MODE,
    ROUND(l.L_EXTENDEDPRICE * (1 - l.L_DISCOUNT), 2) AS NET_AMOUNT,
    ROUND(l.L_EXTENDEDPRICE * (1 - l.L_DISCOUNT) * (1 + l.L_TAX), 2) AS TOTAL_AMOUNT
FROM SNOWFLAKE_SAMPLE_DATA.TPCH_SF1.ORDERS o
JOIN SNOWFLAKE_SAMPLE_DATA.TPCH_SF1.LINEITEM l ON o.O_ORDERKEY = l.L_ORDERKEY;

-- ============================================================================
-- GOLD LAYER: Business-ready aggregates and KPIs
-- ============================================================================

CREATE OR REPLACE TABLE TPCH_DATA_PRODUCT.GOLD.SALES_BY_REGION_MONTH AS
SELECT
    dc.REGION,
    dc.NATION,
    dc.MARKET_SEGMENT,
    DATE_TRUNC('MONTH', f.ORDER_DATE) AS SALES_MONTH,
    COUNT(DISTINCT f.ORDER_KEY) AS TOTAL_ORDERS,
    SUM(f.QUANTITY) AS TOTAL_UNITS_SOLD,
    ROUND(SUM(f.NET_AMOUNT), 2) AS TOTAL_NET_REVENUE,
    ROUND(SUM(f.TOTAL_AMOUNT), 2) AS TOTAL_REVENUE_WITH_TAX,
    ROUND(AVG(f.DISCOUNT) * 100, 2) AS AVG_DISCOUNT_PCT
FROM TPCH_DATA_PRODUCT.CURATED.FCT_ORDER_LINEITEM f
JOIN TPCH_DATA_PRODUCT.CURATED.DIM_CUSTOMER dc ON f.CUSTOMER_KEY = dc.CUSTOMER_KEY
GROUP BY 1, 2, 3, 4;

CREATE OR REPLACE TABLE TPCH_DATA_PRODUCT.GOLD.CUSTOMER_LIFETIME_VALUE AS
SELECT
    dc.CUSTOMER_KEY,
    dc.CUSTOMER_NAME,
    dc.MARKET_SEGMENT,
    dc.NATION,
    dc.REGION,
    COUNT(DISTINCT f.ORDER_KEY) AS TOTAL_ORDERS,
    ROUND(SUM(f.NET_AMOUNT), 2) AS LIFETIME_NET_REVENUE,
    ROUND(AVG(f.NET_AMOUNT), 2) AS AVG_ORDER_VALUE,
    MIN(f.ORDER_DATE) AS FIRST_ORDER_DATE,
    MAX(f.ORDER_DATE) AS LAST_ORDER_DATE,
    DATEDIFF('DAY', MIN(f.ORDER_DATE), MAX(f.ORDER_DATE)) AS CUSTOMER_TENURE_DAYS
FROM TPCH_DATA_PRODUCT.CURATED.FCT_ORDER_LINEITEM f
JOIN TPCH_DATA_PRODUCT.CURATED.DIM_CUSTOMER dc ON f.CUSTOMER_KEY = dc.CUSTOMER_KEY
GROUP BY 1, 2, 3, 4, 5;

CREATE OR REPLACE TABLE TPCH_DATA_PRODUCT.GOLD.SUPPLIER_PERFORMANCE AS
SELECT
    ds.SUPPLIER_KEY,
    ds.SUPPLIER_NAME,
    ds.NATION AS SUPPLIER_NATION,
    ds.REGION AS SUPPLIER_REGION,
    COUNT(DISTINCT f.ORDER_KEY) AS ORDERS_FULFILLED,
    SUM(f.QUANTITY) AS TOTAL_UNITS_SUPPLIED,
    ROUND(SUM(f.NET_AMOUNT), 2) AS TOTAL_REVENUE_GENERATED,
    ROUND(AVG(DATEDIFF('DAY', f.COMMIT_DATE, f.RECEIPT_DATE)), 2) AS AVG_DELIVERY_DELAY_DAYS,
    SUM(CASE WHEN f.RETURN_FLAG = 'R' THEN 1 ELSE 0 END) AS RETURNED_ITEMS,
    ROUND(SUM(CASE WHEN f.RETURN_FLAG = 'R' THEN 1 ELSE 0 END) * 100.0
        / NULLIF(COUNT(*), 0), 2) AS RETURN_RATE_PCT
FROM TPCH_DATA_PRODUCT.CURATED.FCT_ORDER_LINEITEM f
JOIN TPCH_DATA_PRODUCT.CURATED.DIM_SUPPLIER ds ON f.SUPPLIER_KEY = ds.SUPPLIER_KEY
GROUP BY 1, 2, 3, 4;

CREATE OR REPLACE TABLE TPCH_DATA_PRODUCT.GOLD.PRODUCT_SALES_SUMMARY AS
SELECT
    dp.PART_KEY,
    dp.PART_NAME,
    dp.BRAND,
    dp.MANUFACTURER,
    dp.PART_TYPE,
    COUNT(DISTINCT f.ORDER_KEY) AS ORDERS_WITH_PRODUCT,
    SUM(f.QUANTITY) AS TOTAL_QUANTITY_SOLD,
    ROUND(SUM(f.NET_AMOUNT), 2) AS TOTAL_NET_REVENUE,
    ROUND(AVG(f.DISCOUNT) * 100, 2) AS AVG_DISCOUNT_PCT,
    ROUND(SUM(f.NET_AMOUNT) / NULLIF(SUM(f.QUANTITY), 0), 2) AS REVENUE_PER_UNIT
FROM TPCH_DATA_PRODUCT.CURATED.FCT_ORDER_LINEITEM f
JOIN TPCH_DATA_PRODUCT.CURATED.DIM_PART dp ON f.PART_KEY = dp.PART_KEY
GROUP BY 1, 2, 3, 4, 5;

CREATE OR REPLACE TABLE TPCH_DATA_PRODUCT.GOLD.SHIPPING_ANALYSIS AS
SELECT
    f.SHIP_MODE,
    dc.REGION AS CUSTOMER_REGION,
    DATE_TRUNC('QUARTER', f.ORDER_DATE) AS ORDER_QUARTER,
    COUNT(*) AS TOTAL_SHIPMENTS,
    ROUND(AVG(DATEDIFF('DAY', f.ORDER_DATE, f.SHIP_DATE)), 2) AS AVG_DAYS_TO_SHIP,
    ROUND(AVG(DATEDIFF('DAY', f.SHIP_DATE, f.RECEIPT_DATE)), 2) AS AVG_TRANSIT_DAYS,
    ROUND(AVG(DATEDIFF('DAY', f.ORDER_DATE, f.RECEIPT_DATE)), 2) AS AVG_ORDER_TO_DELIVERY_DAYS,
    SUM(CASE WHEN f.RECEIPT_DATE > f.COMMIT_DATE THEN 1 ELSE 0 END) AS LATE_DELIVERIES,
    ROUND(SUM(CASE WHEN f.RECEIPT_DATE > f.COMMIT_DATE THEN 1 ELSE 0 END) * 100.0
        / NULLIF(COUNT(*), 0), 2) AS LATE_DELIVERY_PCT
FROM TPCH_DATA_PRODUCT.CURATED.FCT_ORDER_LINEITEM f
JOIN TPCH_DATA_PRODUCT.CURATED.DIM_CUSTOMER dc ON f.CUSTOMER_KEY = dc.CUSTOMER_KEY
GROUP BY 1, 2, 3;